services:
  memcached:
    image: memcached:latest
    restart: unless-stopped
  webapp:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./files:/opt/rtb/files:rw
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
    restart: unless-stopped
    depends_on:
      - memcached
