services:
  memcached:
    image: memcached:latest
    restart: unless-stopped
    ports:
      - "11211:11211"
  webapp:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./files:/opt/rtb/files:rw
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
      - TZ=America/Chicago
    restart: unless-stopped
    depends_on:
      - memcached
